#!/bin/bash

set -euo pipefail

cmdline="$*"

if [[ "$cmdline" == *"exec --help"* ]]; then
  cat <<'HELP'
Run Codex non-interactively
HELP
  exit 0
fi

workdir=""
args=("$@")
i=0
while [ $i -lt ${#args[@]} ]; do
  a="${args[$i]}"
  if [ "$a" = "-C" ]; then
    i=$((i + 1))
    workdir="${args[$i]:-}"
  fi
  i=$((i + 1))
done

if [ -n "$workdir" ]; then
  cd "$workdir"
fi

prompt="$(cat)"

if [[ "$prompt" == *"Use the \`prd\` skill and then the \`ralph\` skill"* ]]; then
  mkdir -p scripts/ralph/tasks/prds
  cat > scripts/ralph/tasks/prds/prd-hello-prd-ralph.md <<'MD'
# PRD: Hello PRD Ralph Message Update

## Introduction/Overview
Change output from `Hello World` to `Hello PRD Ralph`.

## Goals
- Output exactly `Hello PRD Ralph`.
- Keep implementation to `src/index.ts`.

## User Stories

### US-001: Update greeting string
**Description:** As a developer, I want the greeting changed to `Hello PRD Ralph`.

**Acceptance Criteria:**
- `src/index.ts` logs exactly `Hello PRD Ralph`
- Typecheck passes
- Lint passes
- Tests pass
MD

  cat > scripts/ralph/prd.json <<'JSON'
{
  "project": "smoke-test-project",
  "branchName": "ralph/hello-prd-ralph",
  "description": "Change hello message to Hello PRD Ralph",
  "userStories": [
    {
      "id": "US-001",
      "title": "Update greeting string",
      "description": "As a developer, I want the greeting changed to Hello PRD Ralph.",
      "acceptanceCriteria": [
        "src/index.ts logs exactly Hello PRD Ralph",
        "Typecheck passes",
        "Lint passes",
        "Tests pass"
      ],
      "priority": 1,
      "passes": false,
      "notes": ""
    }
  ]
}
JSON

  cat <<'OUT'
- PRD markdown path: scripts/ralph/tasks/prds/prd-hello-prd-ralph.md
- prd.json path: scripts/ralph/prd.json
- Number of user stories created: 1
OUT
  exit 0
fi

# ralph-sprint.sh PRD generation prompt path extraction.
if [[ "$prompt" == *"Create a complete PRD markdown file at:"* ]]; then
  out_path="$({
    printf '%s\n' "$prompt" | awk '
      /Create a complete PRD markdown file at:/ {capture=1; next}
      capture == 1 {
        if (match($0, /`([^`]+)`/, m)) { print m[1]; exit }
      }
    '
  })"

  if [ -z "$out_path" ]; then
    echo "mock-codex: could not parse markdown output path" >&2
    exit 1
  fi

  mkdir -p "$(dirname "$out_path")"
  cat > "$out_path" <<'MD'
# PRD: Sprint Epic Placeholder

## Introduction/Overview
Generated by smoke mock codex.

## User Stories

### US-001: Placeholder story
**Description:** As a developer, I want a placeholder epic PRD for priming.

**Acceptance Criteria:**
- Typecheck passes
- Lint passes
- Tests pass
MD

  echo "Generated $out_path"
  exit 0
fi

echo "mock-codex: unsupported invocation" >&2
echo "args: $*" >&2
exit 1
